# LIVRO: ALGORÍTOMOS - LÓGICA PARA DESENVOLVIMENTO DE COMPUTADORES 29 EDIÇÃO
# PAULO VICTOR COSTA DE MELO
# 19 DEZEMBRO 2023

# ALUNO DOS CURSOS DE SISTEMAS DE INFORMAÇÃO, TECNÓLOGO EM BANCO DE DADOS, TÉCNICO EM DESENVOLVIMENTO DE SITEMAS
# EXERCICIO COM PRATICAS AUT0DIDATA


# 01 - DADA AS EQUAÇÕES MATEMATICAS A SEGUIR, ESTABELEÇA, PARA CADA UMA DELAS A RESPECTIVA EXPREÇÃO ARITIMÉTICA
# ARQUIVO LAYOUT
